# Series

In [2]:
import pandas as pd
import numpy as np

In [2]:
obj1 = pd.Series([4, 7, -5, 3]) # create a Series from a list
obj1

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
# create a Series from a list with an index
obj2 = pd.Series([4, 7, -5, 3], index = ['a', 'b', 'c', 'd'])
obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [5]:
# or, create a series from a dictionary. keys will be the indice
ave_temp = {'summer': 32, 'winter': 10, 'spring': 20, 'fall': 25}
obj3 = pd.Series(ave_temp)
obj3

summer    32
winter    10
spring    20
fall      25
dtype: int64

In [6]:
print(obj3.values)
print(obj3.index)
# values and index are attributes of the series object

[32 10 20 25]
Index(['summer', 'winter', 'spring', 'fall'], dtype='object')


In [7]:
obj3['summer'] # just like dictionaries, you can access the values by the index

32

In [9]:
obj3.iloc[0] # or, use .iloc to access the values by the position

32

In [10]:
obj3['year'] = 29 # add a value
obj3

summer    32
winter    10
spring    20
fall      25
year      29
dtype: int64

In [11]:
obj3[obj3 > 20]

summer    32
fall      25
year      29
dtype: int64

In [12]:
obj3 * 2

summer    64
winter    20
spring    40
fall      50
year      58
dtype: int64

In [13]:
np.exp(obj3)

summer    7.896296e+13
winter    2.202647e+04
spring    4.851652e+08
fall      7.200490e+10
year      3.931334e+12
dtype: float64

In [14]:
'Chao' in obj3

False

In [15]:
numbers = pd.Series([1., -100., 2., -999., -1000., 3.])
numbers

0       1.0
1    -100.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [16]:
numbers[numbers < 0] # filter out the negative values

1    -100.0
3    -999.0
4   -1000.0
dtype: float64

In [17]:
numbers[numbers < 0].values
# get the values of the negative values

array([ -100.,  -999., -1000.])

In [18]:
with_nans = numbers.replace(numbers[numbers < 0].values, np.nan)
# replace the negative values with NaN
# note that we use the values attribute to get the values of the negative values
# create a new series

In [19]:
with_nans

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [20]:
np.isnan(with_nans) # check if the values are NaN

0    False
1     True
2    False
3     True
4     True
5    False
dtype: bool

In [35]:
# other ways to replace values
numbers.replace([-999, -1000], 1000000) # 1. use a scalar

0          1.0
1       -100.0
2          2.0
3    1000000.0
4    1000000.0
5          3.0
dtype: float64

In [36]:
numbers.replace([-999, -1000], [50, 90]) # 2. use a list

0      1.0
1   -100.0
2      2.0
3     50.0
4     90.0
5      3.0
dtype: float64

In [37]:
numbers.replace({-999: 1000000, -1000: 2000000}) # 3. use a dictionary

0          1.0
1       -100.0
2          2.0
3    1000000.0
4    2000000.0
5          3.0
dtype: float64

In [38]:
numbers  # the original series is not changed

0       1.0
1    -100.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

# DataFrame

## Creating a df from an array

In [36]:
import pandas as pd
import numpy as np

In [2]:
arr1 = np.random.randint(0, 100, 20).reshape(4, 5)
arr1

array([[97, 42, 94, 86, 10],
       [29, 14, 23, 96,  9],
       [89, 27, 83, 64, 82],
       [13, 80, 43, 37, 59]])

In [3]:
df1 = pd.DataFrame(arr1) # create a dataframe from a 2D numpy array
df1

0   1   2   3   4
0  97  42  94  86  10
1  29  14  23  96   9
2  89  27  83  64  82
3  13  80  43  37  59

In [5]:
df1.columns = ['A', 'B', 'C', 'D', 'E'] # set the column names
df1

A   B   C   D   E
0  97  42  94  86  10
1  29  14  23  96   9
2  89  27  83  64  82
3  13  80  43  37  59

In [4]:
rlabels = ["r1", "r2", "r3", "r4"]
clabels = ['c1', 'c2', 'c3', 'c4', 'c5']
# set the row and column names when creating the dataframe
df2 = pd.DataFrame(arr1, index = rlabels, columns = clabels)
df2

c1  c2  c3  c4  c5
r1  97  42  94  86  10
r2  29  14  23  96   9
r3  89  27  83  64  82
r4  13  80  43  37  59

## Creating a df from a dictionary

In [37]:
# create a list of tuples, and then convert to a dataframe
ave_temp = {'summer': 32, 'winter': 10, 'spring': 20, 'fall': 25}
temp_df = pd.DataFrame(list(ave_temp.items()), 
                              columns = ['month', 'temp'])
temp_df

month  temp
0  summer    32
1  winter    10
2  spring    20
3    fall    25

In [38]:
# alternatively
ave_temp2 = {
    'month': list(ave_temp.keys()),
    'temp': list(ave_temp.values()) # values must be equal-length lists
}

temp_df2 = pd.DataFrame(ave_temp2)
temp_df2

month  temp
0  summer    32
1  winter    10
2  spring    20
3    fall    25

In [39]:
# another example
msba_dict = {'course': ['MSBA7001', 'MSBA7002', 'MSBA7003', 'MSBA7004', 'Capstone'],
        'instructor': ['Chao', 'Haipeng', 'Wei', 'Eric', 'Haipeng'],
        'grade': [90, 83, 79, 87.5, 95]}
msba_df = pd.DataFrame(msba_dict)
msba_df

course instructor  grade
0  MSBA7001       Chao   90.0
1  MSBA7002    Haipeng   83.0
2  MSBA7003        Wei   79.0
3  MSBA7004       Eric   87.5
4  Capstone    Haipeng   95.0

In [5]:
msba_df.describe() # only the grade column is numeric values

grade
count   5.000000
mean   86.900000
std     6.188699
min    79.000000
25%    83.000000
50%    87.500000
75%    90.000000
max    95.000000

In [6]:
msba_df.info() # get the information of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   course      5 non-null      object 
 1   instructor  5 non-null      object 
 2   grade       5 non-null      float64
dtypes: float64(1), object(2)
memory usage: 252.0+ bytes


## Selecting columns and adding a new column

In [7]:
msba_df['grade']
# it's a Series

0    90.0
1    83.0
2    79.0
3    87.5
4    95.0
Name: grade, dtype: float64

In [8]:
msba_df.values # get the values of the dataframe. it's an array

array([['MSBA7001', 'Chao', 90.0],
       ['MSBA7002', 'Haipeng', 83.0],
       ['MSBA7003', 'Wei', 79.0],
       ['MSBA7004', 'Eric', 87.5],
       ['Capstone', 'Haipeng', 95.0]], dtype=object)

In [9]:
# or, get the values of a column. also an array
msba_df['grade'].values

array([90. , 83. , 79. , 87.5, 95. ])

In [10]:
# to view multiple columns, insert a list
msba_df[['grade','course']]

grade    course
0   90.0  MSBA7001
1   83.0  MSBA7002
2   79.0  MSBA7003
3   87.5  MSBA7004
4   95.0  Capstone

In [11]:
# you may also use the .append method to view a column
# but it's not recommended as it can be misleading, name or method?
msba_df.grade

0    90.0
1    83.0
2    79.0
3    87.5
4    95.0
Name: grade, dtype: float64

In [46]:
# add a new column called 'attendance'
msba_df['attendance'] = np.random.rand(5).round(1)

In [47]:
msba_df

course instructor  grade  attendance
0  MSBA7001       Chao   90.0         1.0
1  MSBA7002    Haipeng   83.0         0.6
2  MSBA7003        Wei   79.0         0.9
3  MSBA7004       Eric   87.5         0.4
4  Capstone    Haipeng   95.0         0.8

In [48]:
# add a 'fav' column, which is a binary value: 0 or 1
msba_df['fav'] = np.random.randint(0, 2, size = 5)

In [49]:
msba_df

course instructor  grade  attendance  fav
0  MSBA7001       Chao   90.0         1.0    1
1  MSBA7002    Haipeng   83.0         0.6    1
2  MSBA7003        Wei   79.0         0.9    1
3  MSBA7004       Eric   87.5         0.4    1
4  Capstone    Haipeng   95.0         0.8    0

In [50]:
# you may sort the dataframe by a column
msba_df.sort_values(by = 'grade', ascending = False)

course instructor  grade  attendance  fav
4  Capstone    Haipeng   95.0         0.8    0
0  MSBA7001       Chao   90.0         1.0    1
3  MSBA7004       Eric   87.5         0.4    1
1  MSBA7002    Haipeng   83.0         0.6    1
2  MSBA7003        Wei   79.0         0.9    1

In [51]:
sorted(list(msba_df.columns)) # you may also take the columns and sort them

['attendance', 'course', 'fav', 'grade', 'instructor']

## Selecting rows and adding a new row

In [52]:
msba_df.iloc[1] # use .iloc to access a row by index

course        MSBA7002
instructor     Haipeng
grade             83.0
attendance         0.6
fav                  1
Name: 1, dtype: object

In [53]:
msba_df.iloc[[0, 2]] # to view multiple rows, insert a list

course instructor  grade  attendance  fav
0  MSBA7001       Chao   90.0         1.0    1
2  MSBA7003        Wei   79.0         0.9    1

In [54]:
msba_df.iloc[::2] # or, insert a slice

course instructor  grade  attendance  fav
0  MSBA7001       Chao   90.0         1.0    1
2  MSBA7003        Wei   79.0         0.9    1
4  Capstone    Haipeng   95.0         0.8    0

In [55]:
msba_df.iloc[::2]['course'] # continue to view a column

0    MSBA7001
2    MSBA7003
4    Capstone
Name: course, dtype: object

In [22]:
msba_df.loc[::2, 'course'] # or, use the .loc method whenever a name is used

0    MSBA7001
2    MSBA7003
4    Capstone
Name: course, dtype: object

In [56]:
# use loc to add a row like adding a key-value pair.
# iloc would not work because the index 5 does not exist.
msba_df.loc[len(msba_df)] = ['MSBA7027', 'Zhengli', 89, 0.8, 1]

In [57]:
msba_df

course instructor  grade  attendance  fav
0  MSBA7001       Chao   90.0         1.0    1
1  MSBA7002    Haipeng   83.0         0.6    1
2  MSBA7003        Wei   79.0         0.9    1
3  MSBA7004       Eric   87.5         0.4    1
4  Capstone    Haipeng   95.0         0.8    0
5  MSBA7027    Zhengli   89.0         0.8    1

In [58]:
msba_df.index

Index([0, 1, 2, 3, 4, 5], dtype='int64')

## Selecting values from a df

In [59]:
# if only filtering the rows, you may simply use []
msba_df[msba_df['grade'] >= 90]

course instructor  grade  attendance  fav
0  MSBA7001       Chao   90.0         1.0    1
4  Capstone    Haipeng   95.0         0.8    0

In [60]:
msba_df[msba_df['fav'] == 1.0]

course instructor  grade  attendance  fav
0  MSBA7001       Chao   90.0         1.0    1
1  MSBA7002    Haipeng   83.0         0.6    1
2  MSBA7003        Wei   79.0         0.9    1
3  MSBA7004       Eric   87.5         0.4    1
5  MSBA7027    Zhengli   89.0         0.8    1

In [61]:
# use parentheses to enclose conditions
msba_df[(msba_df['grade'] >= 90) & (msba_df['fav'] == 1.0)]

course instructor  grade  attendance  fav
0  MSBA7001       Chao   90.0         1.0    1

In [62]:
msba_df[~(msba_df['grade'] >= 90)] # ~ means NOT

course instructor  grade  attendance  fav
1  MSBA7002    Haipeng   83.0         0.6    1
2  MSBA7003        Wei   79.0         0.9    1
3  MSBA7004       Eric   87.5         0.4    1
5  MSBA7027    Zhengli   89.0         0.8    1

In [63]:
# to filter by both row and column, use .loc
msba_df.loc[msba_df['fav'] == 1.0, 'course']

0    MSBA7001
1    MSBA7002
2    MSBA7003
3    MSBA7004
5    MSBA7027
Name: course, dtype: object

In [64]:
# filter applies on the column name, not on the values.
msba_df.filter(regex = 'e$')
# filter out the columns that end with 'e'

course  grade  attendance
0  MSBA7001   90.0         1.0
1  MSBA7002   83.0         0.6
2  MSBA7003   79.0         0.9
3  MSBA7004   87.5         0.4
4  Capstone   95.0         0.8
5  MSBA7027   89.0         0.8

## Removing rows and columns from a df

In [65]:
msba_df.drop('grade', axis=1) # to delete a column

course instructor  attendance  fav
0  MSBA7001       Chao         1.0    1
1  MSBA7002    Haipeng         0.6    1
2  MSBA7003        Wei         0.9    1
3  MSBA7004       Eric         0.4    1
4  Capstone    Haipeng         0.8    0
5  MSBA7027    Zhengli         0.8    1

In [66]:
msba_df # it does not change the original df

course instructor  grade  attendance  fav
0  MSBA7001       Chao   90.0         1.0    1
1  MSBA7002    Haipeng   83.0         0.6    1
2  MSBA7003        Wei   79.0         0.9    1
3  MSBA7004       Eric   87.5         0.4    1
4  Capstone    Haipeng   95.0         0.8    0
5  MSBA7027    Zhengli   89.0         0.8    1

In [67]:
msba_df2 = msba_df.drop('grade', axis=1).copy() # make a copy to a new df

In [68]:
msba_df2

course instructor  attendance  fav
0  MSBA7001       Chao         1.0    1
1  MSBA7002    Haipeng         0.6    1
2  MSBA7003        Wei         0.9    1
3  MSBA7004       Eric         0.4    1
4  Capstone    Haipeng         0.8    0
5  MSBA7027    Zhengli         0.8    1

In [69]:
# use apply to apply a function to a column or row
msba_df2['attendance'] = msba_df2['attendance'].apply(lambda x: x + 0.1)

In [70]:
msba_df2

course instructor  attendance  fav
0  MSBA7001       Chao         1.1    1
1  MSBA7002    Haipeng         0.7    1
2  MSBA7003        Wei         1.0    1
3  MSBA7004       Eric         0.5    1
4  Capstone    Haipeng         0.9    0
5  MSBA7027    Zhengli         0.9    1

## `NaN`

In [71]:
msba_df3 = msba_df.copy()

In [72]:
msba_df3

course instructor  grade  attendance  fav
0  MSBA7001       Chao   90.0         1.0    1
1  MSBA7002    Haipeng   83.0         0.6    1
2  MSBA7003        Wei   79.0         0.9    1
3  MSBA7004       Eric   87.5         0.4    1
4  Capstone    Haipeng   95.0         0.8    0
5  MSBA7027    Zhengli   89.0         0.8    1

In [73]:
msba_df3.loc[3, ['grade', 'fav']] = np.nan

In [74]:
msba_df3

course instructor  grade  attendance  fav
0  MSBA7001       Chao   90.0         1.0  1.0
1  MSBA7002    Haipeng   83.0         0.6  1.0
2  MSBA7003        Wei   79.0         0.9  1.0
3  MSBA7004       Eric    NaN         0.4  NaN
4  Capstone    Haipeng   95.0         0.8  0.0
5  MSBA7027    Zhengli   89.0         0.8  1.0

In [75]:
msba_df3.isnull()
# pd.DataFrame.isna also works the same

course  instructor  grade  attendance    fav
0   False       False  False       False  False
1   False       False  False       False  False
2   False       False  False       False  False
3   False       False   True       False   True
4   False       False  False       False  False
5   False       False  False       False  False

In [76]:
# to see the number of missing values in each row
msba_df3.isnull().sum(axis = 1)

0    0
1    0
2    0
3    2
4    0
5    0
dtype: int64

In [77]:
# to find out the row indices of NaN values
msba_df3[msba_df3.isnull().any(axis = 1)].index

Index([3], dtype='int64')

In [78]:
# to see if any column has missing values
msba_df3.isnull().any()

course        False
instructor    False
grade          True
attendance    False
fav            True
dtype: bool

In [81]:
# use ffill or bfill to fill NaN values
msba_df3['grade'].ffill(), msba_df3['fav'].bfill()

(0    90.0
 1    83.0
 2    79.0
 3    79.0
 4    95.0
 5    89.0
 Name: grade, dtype: float64,
 0    1.0
 1    1.0
 2    1.0
 3    0.0
 4    0.0
 5    1.0
 Name: fav, dtype: float64)

In [80]:
msba_df3 # it does not change the original df

course instructor  grade  attendance  fav
0  MSBA7001       Chao   90.0         1.0  1.0
1  MSBA7002    Haipeng   83.0         0.6  1.0
2  MSBA7003        Wei   79.0         0.9  1.0
3  MSBA7004       Eric    NaN         0.4  NaN
4  Capstone    Haipeng   95.0         0.8  0.0
5  MSBA7027    Zhengli   89.0         0.8  1.0

In [82]:
# pd.DataFrame.interpolate or pd.Series.interpolate
# insert new values to replace NaN based on various methods
msba_df3['grade'].interpolate(method = 'linear', axis = 0)
# the NaN value is replaced by the ave of its neighbors along axis 0.

0    90.0
1    83.0
2    79.0
3    87.0
4    95.0
5    89.0
Name: grade, dtype: float64

## Date & Time

In [83]:
examtime = pd.Timestamp('2024-09-04 15:30:00')
module1 = pd.date_range(start = '2024/08/30', periods = 10, freq = '4D')
period = pd.Period('2024-10-04', freq = 'M')
arrival = pd.to_datetime('12-11-2025 15:27', format ='%d-%m-%Y %H:%M')

In [84]:
examtime

Timestamp('2024-09-04 15:30:00')

In [85]:
module1

DatetimeIndex(['2024-08-30', '2024-09-03', '2024-09-07', '2024-09-11',
               '2024-09-15', '2024-09-19', '2024-09-23', '2024-09-27',
               '2024-10-01', '2024-10-05'],
              dtype='datetime64[ns]', freq='4D')

In [86]:
module1 > examtime

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [87]:
examtime.month, examtime.is_month_end

(9, False)

In [88]:
arrival.month, arrival.daysinmonth

(11, 30)

In [89]:
for day in pd.date_range('2025-10-02', periods = 7, freq = 'ME'):
    print(day.day_of_week, day.day_name(), day.date())

4 Friday 2025-10-31
6 Sunday 2025-11-30
2 Wednesday 2025-12-31
5 Saturday 2026-01-31
5 Saturday 2026-02-28
1 Tuesday 2026-03-31
3 Thursday 2026-04-30


## Reading from CSV files

In [5]:
advertising = pd.read_csv('../data_in/advertising.csv', index_col = 0)

In [7]:
advertising.head(3)

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3

In [9]:
advertising.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 1 to 200
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 7.8 KB


In [11]:
advertising['TV'].agg(['min', 'max', 'mean', 'median', 'std'])

min         0.700000
max       296.400000
mean      147.042500
median    149.750000
std        85.854236
Name: TV, dtype: float64

In [15]:
# apply a function to a column
advertising['sales'].apply(lambda x: x + 3).iloc[:5]

1    25.1
2    13.4
3    12.3
4    21.5
5    15.9
Name: sales, dtype: float64

In [17]:
# find the moving sum at an interval of 3
advertising['radio'].rolling(3).sum().iloc[:5]

1      NaN
2      NaN
3    123.0
4    126.5
5     98.0
Name: radio, dtype: float64

In [19]:
# transform the sales column to two new columns by applying two functions
advertising['sales'].transform(['sqrt', lambda x: x % 10]).iloc[:5]

sqrt  <lambda>
1  4.701064       2.1
2  3.224903       0.4
3  3.049590       9.3
4  4.301163       8.5
5  3.591657       2.9

## Writing to a CSV file

In [96]:
msba_df.to_csv('../data_out/msba.csv')

In [97]:
msba_df.to_csv('../data_out/msba_no_header.csv', sep = ',', index = False, header = False)